-- Advanced paired words: pair_id 41-60 (20 pairs = 40 rows)
-- 일상에서 쓰이나 더 세밀한 뉘앙스의 동사
insert into words (english, korean_vi, korean_vt, type, pair_id, level) values
('stick',     '붙다',          null,                  'Vi', 41, 'advanced'),
('stick',     null,            '~을 붙이다',          'Vt', 41, 'advanced'),
('charge',    '충전되다',      null,                  'Vi', 42, 'advanced'),
('charge',    null,            '~을 충전하다',        'Vt', 42, 'advanced'),
('block',     '막히다',        null,                  'Vi', 43, 'advanced'),
('block',     null,            '~을 막다',            'Vt', 43, 'advanced'),
('split',     '나뉘다',        null,                  'Vi', 44, 'advanced'),
('split',     null,            '~을 나누다',          'Vt', 44, 'advanced'),
('gather',    '모이다',        null,                  'Vi', 45, 'advanced'),
('gather',    null,            '~을 모으다',          'Vt', 45, 'advanced'),
('pour',      '쏟아지다',      null,                  'Vi', 46, 'advanced'),
('pour',      null,            '~을 붓다',            'Vt', 46, 'advanced'),
('drain',     '빠지다',        null,                  'Vi', 47, 'advanced'),
('drain',     null,            '~을 빼다',            'Vt', 47, 'advanced'),
('settle',    '자리를 잡다',   null,                  'Vi', 48, 'advanced'),
('settle',    null,            '~을 해결하다',        'Vt', 48, 'advanced'),
('boil',      '끓다',          null,                  'Vi', 49, 'advanced'),
('boil',      null,            '~을 끓이다',          'Vt', 49, 'advanced'),
('freeze',    '얼다',          null,                  'Vi', 50, 'advanced'),
('freeze',    null,            '~을 얼리다',          'Vt', 50, 'advanced'),
('shrink',    '줄어들다',      null,                  'Vi', 51, 'advanced'),
('shrink',    null,            '~을 줄이다',          'Vt', 51, 'advanced'),
('sink',      '가라앉다',      null,                  'Vi', 52, 'advanced'),
('sink',      null,            '~을 가라앉히다',      'Vt', 52, 'advanced'),
('float',     '떠다니다',      null,                  'Vi', 53, 'advanced'),
('float',     null,            '~을 띄우다',          'Vt', 53, 'advanced'),
('fit',       '맞다',          null,                  'Vi', 54, 'advanced'),
('fit',       null,            '~에 맞추다',          'Vt', 54, 'advanced'),
('ring',      '울리다',        null,                  'Vi', 55, 'advanced'),
('ring',      null,            '~에게 전화하다',      'Vt', 55, 'advanced'),
('tie',       '묶이다',        null,                  'Vi', 56, 'advanced'),
('tie',       null,            '~을 묶다',            'Vt', 56, 'advanced'),
('peel',      '벗겨지다',      null,                  'Vi', 57, 'advanced'),
('peel',      null,            '~을 벗기다',          'Vt', 57, 'advanced'),
('form',      '형성되다',      null,                  'Vi', 58, 'advanced'),
('form',      null,            '~을 형성하다',        'Vt', 58, 'advanced'),
('increase',  '증가하다',      null,                  'Vi', 59, 'advanced'),
('increase',  null,            '~을 증가시키다',      'Vt', 59, 'advanced'),
('develop',   '발전하다',      null,                  'Vi', 60, 'advanced'),
('develop',   null,            '~을 발전시키다',      'Vt', 60, 'advanced');

-- Advanced Vi-only (30) - 표정/몸짓/심리 표현 동사
insert into words (english, korean_vi, korean_vt, type, pair_id, level) values
('argue',     '언쟁하다',        null, 'Vi', null, 'advanced'),
('calm',      '진정되다',        null, 'Vi', null, 'advanced'),
('wander',    '돌아다니다',      null, 'Vi', null, 'advanced'),
('stroll',    '산책하다',        null, 'Vi', null, 'advanced'),
('nap',       '낮잠을 자다',     null, 'Vi', null, 'advanced'),
('doze',      '졸다',            null, 'Vi', null, 'advanced'),
('glare',     '노려보다',        null, 'Vi', null, 'advanced'),
('sob',       '흐느끼다',        null, 'Vi', null, 'advanced'),
('whisper',   '속삭이다',        null, 'Vi', null, 'advanced'),
('shout',     '소리치다',        null, 'Vi', null, 'advanced'),
('scream',    '비명을 지르다',   null, 'Vi', null, 'advanced'),
('sigh',      '한숨을 쉬다',     null, 'Vi', null, 'advanced'),
('yawn',      '하품하다',        null, 'Vi', null, 'advanced'),
('groan',     '신음하다',        null, 'Vi', null, 'advanced'),
('frown',     '얼굴을 찌푸리다', null, 'Vi', null, 'advanced'),
('blush',     '얼굴이 빨개지다', null, 'Vi', null, 'advanced'),
('tremble',   '떨리다',          null, 'Vi', null, 'advanced'),
('stumble',   '비틀거리다',      null, 'Vi', null, 'advanced'),
('limp',      '절뚝거리다',      null, 'Vi', null, 'advanced'),
('pace',      '서성이다',        null, 'Vi', null, 'advanced'),
('pause',     '잠시 멈추다',     null, 'Vi', null, 'advanced'),
('linger',    '오래 머물다',     null, 'Vi', null, 'advanced'),
('wink',      '윙크하다',        null, 'Vi', null, 'advanced'),
('snore',     '코를 골다',       null, 'Vi', null, 'advanced'),
('giggle',    '깔깔 웃다',       null, 'Vi', null, 'advanced'),
('chuckle',   '낄낄 웃다',       null, 'Vi', null, 'advanced'),
('gossip',    '험담하다',        null, 'Vi', null, 'advanced'),
('flirt',     '추파를 던지다',   null, 'Vi', null, 'advanced'),
('boast',     '자랑하다',        null, 'Vi', null, 'advanced'),
('sulk',      '토라지다',        null, 'Vi', null, 'advanced');

-- Advanced Vt-only (30) - 관계/감정 표현 동사
insert into words (english, korean_vi, korean_vt, type, pair_id, level) values
('hug',        null, '~을 안다',             'Vt', null, 'advanced'),
('kiss',       null, '~에 키스하다',         'Vt', null, 'advanced'),
('scratch',    null, '~을 긁다',             'Vt', null, 'advanced'),
('slap',       null, '~을 때리다',           'Vt', null, 'advanced'),
('grab',       null, '~을 잡아당기다',       'Vt', null, 'advanced'),
('squeeze',    null, '~을 꽉 쥐다',          'Vt', null, 'advanced'),
('release',    null, '~을 놓아주다',         'Vt', null, 'advanced'),
('toss',       null, '~을 가볍게 던지다',    'Vt', null, 'advanced'),
('borrow',     null, '~을 빌리다',           'Vt', null, 'advanced'),
('lend',       null, '~을 빌려주다',         'Vt', null, 'advanced'),
('spend',      null, '~을 쓰다',             'Vt', null, 'advanced'),
('save',       null, '~을 아끼다',           'Vt', null, 'advanced'),
('waste',      null, '~을 낭비하다',         'Vt', null, 'advanced'),
('earn',       null, '~을 벌다',             'Vt', null, 'advanced'),
('owe',        null, '~에게 빚지다',         'Vt', null, 'advanced'),
('avoid',      null, '~을 피하다',           'Vt', null, 'advanced'),
('chase',      null, '~을 쫓다',             'Vt', null, 'advanced'),
('defeat',     null, '~을 이기다',           'Vt', null, 'advanced'),
('trick',      null, '~을 속이다',           'Vt', null, 'advanced'),
('tease',      null, '~을 놀리다',           'Vt', null, 'advanced'),
('comfort',    null, '~을 위로하다',         'Vt', null, 'advanced'),
('greet',      null, '~에게 인사하다',       'Vt', null, 'advanced'),
('interrupt',  null, '~을 방해하다',         'Vt', null, 'advanced'),
('bother',     null, '~을 귀찮게 하다',      'Vt', null, 'advanced'),
('blame',      null, '~을 비난하다',         'Vt', null, 'advanced'),
('praise',     null, '~을 칭찬하다',         'Vt', null, 'advanced'),
('reward',     null, '~에게 보상하다',       'Vt', null, 'advanced'),
('ignore',     null, '~을 무시하다',         'Vt', null, 'advanced'),
('expect',     null, '~을 기대하다',         'Vt', null, 'advanced'),
('trust',      null, '~을 믿다',             'Vt', null, 'advanced');
