-- Paired words: 20 pairs = 40 rows
insert into words (english, korean_vi, korean_vt, type, pair_id) values
('rise',   '오르다',    null,          'Vi', 1),
('raise',  null,        '~을 올리다',  'Vt', 1),
('lie',    '눕다',      null,          'Vi', 2),
('lay',    null,        '~을 놓다',    'Vt', 2),
('sit',    '앉다',      null,          'Vi', 3),
('set',    null,        '~을 설정하다','Vt', 3),
('fall',   '떨어지다',  null,          'Vi', 4),
('fell',   null,        '~을 쓰러뜨리다','Vt', 4),
('come',   '오다',      null,          'Vi', 5),
('bring',  null,        '~을 가져오다','Vt', 5),
('go',     '가다',      null,          'Vi', 6),
('take',   null,        '~을 가져가다','Vt', 6),
('appear', '나타나다',  null,          'Vi', 7),
('show',   null,        '~을 보여주다','Vt', 7),
('grow',   '자라다',    null,          'Vi', 8),
('grow',   null,        '~을 기르다',  'Vt', 8),
('hang',   '매달리다',  null,          'Vi', 9),
('hang',   null,        '~을 걸다',    'Vt', 9),
('run',    '달리다',    null,          'Vi', 10),
('run',    null,        '~을 운영하다','Vt', 10),
('turn',   '돌다',      null,          'Vi', 11),
('turn',   null,        '~을 돌리다',  'Vt', 11),
('move',   '움직이다',  null,          'Vi', 12),
('move',   null,        '~을 옮기다',  'Vt', 12),
('open',   '열리다',    null,          'Vi', 13),
('open',   null,        '~을 열다',    'Vt', 13),
('close',  '닫히다',    null,          'Vi', 14),
('close',  null,        '~을 닫다',    'Vt', 14),
('change', '변하다',    null,          'Vi', 15),
('change', null,        '~을 바꾸다',  'Vt', 15),
('break',  '부러지다',  null,          'Vi', 16),
('break',  null,        '~을 부수다',  'Vt', 16),
('stop',   '멈추다',    null,          'Vi', 17),
('stop',   null,        '~을 멈추다',  'Vt', 17),
('start',  '시작되다',  null,          'Vi', 18),
('start',  null,        '~을 시작하다','Vt', 18),
('spread', '퍼지다',    null,          'Vi', 19),
('spread', null,        '~을 퍼뜨리다','Vt', 19),
('burn',   '타다',      null,          'Vi', 20),
('burn',   null,        '~을 태우다',  'Vt', 20);

-- Pure Vi: 30 rows
insert into words (english, korean_vi, korean_vt, type, pair_id) values
('arrive',      '도착하다',   null, 'Vi', null),
('depart',      '출발하다',   null, 'Vi', null),
('emerge',      '나타나다',   null, 'Vi', null),
('exist',       '존재하다',   null, 'Vi', null),
('occur',       '발생하다',   null, 'Vi', null),
('happen',      '일어나다',   null, 'Vi', null),
('disappear',   '사라지다',   null, 'Vi', null),
('agree',       '동의하다',   null, 'Vi', null),
('succeed',     '성공하다',   null, 'Vi', null),
('fail',        '실패하다',   null, 'Vi', null),
('sleep',       '자다',       null, 'Vi', null),
('wake',        '깨다',       null, 'Vi', null),
('die',         '죽다',       null, 'Vi', null),
('live',        '살다',       null, 'Vi', null),
('swim',        '수영하다',   null, 'Vi', null),
('fly',         '날다',       null, 'Vi', null),
('walk',        '걷다',       null, 'Vi', null),
('jump',        '뛰다',       null, 'Vi', null),
('laugh',       '웃다',       null, 'Vi', null),
('cry',         '울다',       null, 'Vi', null),
('wait',        '기다리다',   null, 'Vi', null),
('work',        '일하다',     null, 'Vi', null),
('play',        '놀다',       null, 'Vi', null),
('smile',       '미소 짓다',  null, 'Vi', null),
('stand',       '서다',       null, 'Vi', null),
('kneel',       '무릎 꿇다',  null, 'Vi', null),
('cough',       '기침하다',   null, 'Vi', null),
('sneeze',      '재채기하다', null, 'Vi', null),
('hesitate',    '망설이다',   null, 'Vi', null),
('participate', '참가하다',   null, 'Vi', null);

-- Pure Vt: 30 rows
insert into words (english, korean_vi, korean_vt, type, pair_id) values
('discuss',   null, '~을 논의하다',       'Vt', null),
('mention',   null, '~을 언급하다',       'Vt', null),
('resemble',  null, '~을 닮다',           'Vt', null),
('contact',   null, '~에 연락하다',       'Vt', null),
('reach',     null, '~에 닿다',           'Vt', null),
('marry',     null, '~와 결혼하다',       'Vt', null),
('approach',  null, '~에 접근하다',       'Vt', null),
('enter',     null, '~에 들어가다',       'Vt', null),
('answer',    null, '~에 답하다',         'Vt', null),
('call',      null, '~을 부르다',         'Vt', null),
('help',      null, '~을 돕다',           'Vt', null),
('make',      null, '~을 만들다',         'Vt', null),
('create',    null, '~을 창조하다',       'Vt', null),
('build',     null, '~을 짓다',           'Vt', null),
('destroy',   null, '~을 파괴하다',       'Vt', null),
('find',      null, '~을 찾다',           'Vt', null),
('lose',      null, '~을 잃다',           'Vt', null),
('keep',      null, '~을 유지하다',       'Vt', null),
('send',      null, '~을 보내다',         'Vt', null),
('give',      null, '~을 주다',           'Vt', null),
('tell',      null, '~에게 말하다',       'Vt', null),
('ask',       null, '~에게 묻다',         'Vt', null),
('use',       null, '~을 사용하다',       'Vt', null),
('need',      null, '~을 필요로 하다',    'Vt', null),
('want',      null, '~을 원하다',         'Vt', null),
('like',      null, '~을 좋아하다',       'Vt', null),
('love',      null, '~을 사랑하다',       'Vt', null),
('hate',      null, '~을 싫어하다',       'Vt', null),
('know',      null, '~을 알다',           'Vt', null),
('consider',  null, '~을 고려하다',       'Vt', null);
