-- Intermediate paired words: pair_id 21-40 (20 pairs = 40 rows)
-- 일상에서 자주 쓰이는 상태변화/동작 동사
insert into words (english, korean_vi, korean_vt, type, pair_id, level) values
('melt',     '녹다',          null,                  'Vi', 21, 'intermediate'),
('melt',     null,            '~을 녹이다',          'Vt', 21, 'intermediate'),
('dry',      '마르다',        null,                  'Vi', 22, 'intermediate'),
('dry',      null,            '~을 말리다',          'Vt', 22, 'intermediate'),
('cool',     '식다',          null,                  'Vi', 23, 'intermediate'),
('cool',     null,            '~을 식히다',          'Vt', 23, 'intermediate'),
('fill',     '가득 차다',     null,                  'Vi', 24, 'intermediate'),
('fill',     null,            '~을 채우다',          'Vt', 24, 'intermediate'),
('spill',    '쏟아지다',      null,                  'Vi', 25, 'intermediate'),
('spill',    null,            '~을 쏟다',            'Vt', 25, 'intermediate'),
('drop',     '떨어지다',      null,                  'Vi', 26, 'intermediate'),
('drop',     null,            '~을 떨어뜨리다',      'Vt', 26, 'intermediate'),
('roll',     '구르다',        null,                  'Vi', 27, 'intermediate'),
('roll',     null,            '~을 굴리다',          'Vt', 27, 'intermediate'),
('shake',    '흔들리다',      null,                  'Vi', 28, 'intermediate'),
('shake',    null,            '~을 흔들다',          'Vt', 28, 'intermediate'),
('hide',     '숨다',          null,                  'Vi', 29, 'intermediate'),
('hide',     null,            '~을 숨기다',          'Vt', 29, 'intermediate'),
('lock',     '잠기다',        null,                  'Vi', 30, 'intermediate'),
('lock',     null,            '~을 잠그다',          'Vt', 30, 'intermediate'),
('tear',     '찢어지다',      null,                  'Vi', 31, 'intermediate'),
('tear',     null,            '~을 찢다',            'Vt', 31, 'intermediate'),
('bend',     '휘다',          null,                  'Vi', 32, 'intermediate'),
('bend',     null,            '~을 구부리다',        'Vt', 32, 'intermediate'),
('hurt',     '아프다',        null,                  'Vi', 33, 'intermediate'),
('hurt',     null,            '~을 다치게 하다',     'Vt', 33, 'intermediate'),
('mix',      '섞이다',        null,                  'Vi', 34, 'intermediate'),
('mix',      null,            '~을 섞다',            'Vt', 34, 'intermediate'),
('heat',     '뜨거워지다',    null,                  'Vi', 35, 'intermediate'),
('heat',     null,            '~을 데우다',          'Vt', 35, 'intermediate'),
('light',    '켜지다',        null,                  'Vi', 36, 'intermediate'),
('light',    null,            '~을 켜다',            'Vt', 36, 'intermediate'),
('fold',     '접히다',        null,                  'Vi', 37, 'intermediate'),
('fold',     null,            '~을 접다',            'Vt', 37, 'intermediate'),
('connect',  '연결되다',      null,                  'Vi', 38, 'intermediate'),
('connect',  null,            '~을 연결하다',        'Vt', 38, 'intermediate'),
('cover',    '덮이다',        null,                  'Vi', 39, 'intermediate'),
('cover',    null,            '~을 덮다',            'Vt', 39, 'intermediate'),
('stretch',  '늘어나다',      null,                  'Vi', 40, 'intermediate'),
('stretch',  null,            '~을 늘이다',          'Vt', 40, 'intermediate');

-- Intermediate Vi-only (30) - 일상 행동/감정 동사
insert into words (english, korean_vi, korean_vt, type, pair_id, level) values
('travel',    '여행하다',     null, 'Vi', null, 'intermediate'),
('dance',     '춤추다',       null, 'Vi', null, 'intermediate'),
('sing',      '노래하다',     null, 'Vi', null, 'intermediate'),
('talk',      '이야기하다',   null, 'Vi', null, 'intermediate'),
('listen',    '귀 기울이다',  null, 'Vi', null, 'intermediate'),
('look',      '바라보다',     null, 'Vi', null, 'intermediate'),
('worry',     '걱정하다',     null, 'Vi', null, 'intermediate'),
('relax',     '긴장을 풀다',  null, 'Vi', null, 'intermediate'),
('rush',      '서두르다',     null, 'Vi', null, 'intermediate'),
('slip',      '미끄러지다',   null, 'Vi', null, 'intermediate'),
('survive',   '살아남다',     null, 'Vi', null, 'intermediate'),
('escape',    '탈출하다',     null, 'Vi', null, 'intermediate'),
('recover',   '회복하다',     null, 'Vi', null, 'intermediate'),
('wonder',    '궁금해하다',   null, 'Vi', null, 'intermediate'),
('react',     '반응하다',     null, 'Vi', null, 'intermediate'),
('respond',   '응답하다',     null, 'Vi', null, 'intermediate'),
('exercise',  '운동하다',     null, 'Vi', null, 'intermediate'),
('nod',       '고개를 끄덕이다', null, 'Vi', null, 'intermediate'),
('wave',      '손을 흔들다',  null, 'Vi', null, 'intermediate'),
('breathe',   '숨 쉬다',      null, 'Vi', null, 'intermediate'),
('blink',     '눈을 깜빡이다', null, 'Vi', null, 'intermediate'),
('shiver',    '몸을 떨다',    null, 'Vi', null, 'intermediate'),
('sweat',     '땀 흘리다',    null, 'Vi', null, 'intermediate'),
('struggle',  '애쓰다',       null, 'Vi', null, 'intermediate'),
('cope',      '대처하다',     null, 'Vi', null, 'intermediate'),
('chat',      '수다를 떨다',  null, 'Vi', null, 'intermediate'),
('complain',  '불평하다',     null, 'Vi', null, 'intermediate'),
('apologize', '사과하다',     null, 'Vi', null, 'intermediate'),
('volunteer', '자원하다',     null, 'Vi', null, 'intermediate'),
('compete',   '경쟁하다',     null, 'Vi', null, 'intermediate');

-- Intermediate Vt-only (30) - 일상 행동 동사
insert into words (english, korean_vi, korean_vt, type, pair_id, level) values
('push',      null, '~을 밀다',          'Vt', null, 'intermediate'),
('pull',      null, '~을 당기다',        'Vt', null, 'intermediate'),
('lift',      null, '~을 들어올리다',    'Vt', null, 'intermediate'),
('throw',     null, '~을 던지다',        'Vt', null, 'intermediate'),
('pick',      null, '~을 집다',          'Vt', null, 'intermediate'),
('wash',      null, '~을 씻다',          'Vt', null, 'intermediate'),
('clean',     null, '~을 청소하다',      'Vt', null, 'intermediate'),
('fix',       null, '~을 고치다',        'Vt', null, 'intermediate'),
('cook',      null, '~을 요리하다',      'Vt', null, 'intermediate'),
('cut',       null, '~을 자르다',        'Vt', null, 'intermediate'),
('kick',      null, '~을 차다',          'Vt', null, 'intermediate'),
('try',       null, '~을 시도하다',      'Vt', null, 'intermediate'),
('touch',     null, '~을 만지다',        'Vt', null, 'intermediate'),
('watch',     null, '~을 지켜보다',      'Vt', null, 'intermediate'),
('miss',      null, '~을 그리워하다',    'Vt', null, 'intermediate'),
('join',      null, '~에 참가하다',      'Vt', null, 'intermediate'),
('follow',    null, '~을 따라가다',      'Vt', null, 'intermediate'),
('pass',      null, '~을 지나치다',      'Vt', null, 'intermediate'),
('forget',    null, '~을 잊다',          'Vt', null, 'intermediate'),
('remember',  null, '~을 기억하다',      'Vt', null, 'intermediate'),
('choose',    null, '~을 선택하다',      'Vt', null, 'intermediate'),
('meet',      null, '~을 만나다',        'Vt', null, 'intermediate'),
('check',     null, '~을 확인하다',      'Vt', null, 'intermediate'),
('enjoy',     null, '~을 즐기다',        'Vt', null, 'intermediate'),
('finish',    null, '~을 끝내다',        'Vt', null, 'intermediate'),
('plan',      null, '~을 계획하다',      'Vt', null, 'intermediate'),
('share',     null, '~을 공유하다',      'Vt', null, 'intermediate'),
('protect',   null, '~을 보호하다',      'Vt', null, 'intermediate'),
('feel',      null, '~을 느끼다',        'Vt', null, 'intermediate'),
('paint',     null, '~을 칠하다',        'Vt', null, 'intermediate');
